[Settings]
  ID = "gender-survey-dashboard"

[build]
  base    = "src/app"
  publish = "build"
  command = "../../scripts/cibuild"
  ignore = "false"

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
