#!/bin/bash

set -e

if [[ -n "${FB_GENDER_SURVEY_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Run linters on the project's code
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        if command -v docker-compose &> /dev/null; then
            # Lint Bash scripts
            docker-compose \
                run --rm --no-deps shellcheck \
                scripts/*

            # Lint JavaScript
            docker-compose \
                run --rm --no-deps -e CI app \
                yarn lint
        fi
    fi
fi
